version: '3'
#versienummer
#service= in deze sectie worden de containers 
#die worden gestart als dockercompose instantie
services:

  db:
    image: mysql:latest 
    container_name: db 
    restart: always
    environment: 
      MYSQL_USER: sabahattin
      MYSQL_ROOT_PASSWORD: Welkom01!
      MYSQL_PASSWORD: Welkom01!
      MYSQL_DATABASE: sabahattin 
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - wpsite   
   
  go:
    image: stunc/loanwebsite:latest
    #build: 
      #context: .  huidig directory
    container_name: loanwebsite
    ports: 
      - "8095:8095"
    depends_on: 
      - "db"
    networks:
      - wpsite  

# phpMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    restart: always
    ports:
      - '8085:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Welkom01!      
    networks:
      - wpsite  
 
networks:
  wpsite:
volumes: # add volume to persist data.
  my-db:
